### ISSUE TITLE
ui-fixes/ Button Component

### ISSUE THREAD

**Issue by QUDBS** [secretkeylabs/xverse-web-extension#57]
There are some irregularities between buttons on different screens, and the states (hover etc) are absent.

**All buttons:**
- [ ] Text: Satoshi Bold 12px, #FFFFFF without transparency
- [ ] Radius 8px
- [ ] 44px height

All the specs for components (states and behaviors) are listed here: 
https://www.figma.com/file/eUJAc1beEvNcLPGszkY1xo/Xverse-%E2%80%94-Extension?node-id=1068%3A48482

**Primary button (blue one):**
- [ ] Hover: color turn to #6977F8

**Secondary button:** 
- [ ] Secondary button border should be in #4C5187
- [ ] Secondary button hover: the inside fills with #4C5187 20% opacity
